layout_spectrum: 0.4856881
typography_spectrum: 0.7254362
color:
  saturation: 0.4302796
  lightness: 0.008363632
  brandStrength: 0.4175333
  rhythmicContrast: 0.6301376
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Mm1
